services:
  billing:
    container_name: movies-notifications
    image: ghcr.io/nikolayshvets/movies-notifications:1.1
    env_file:
      - .env
    volumes:
      - ./log:/var/log
    restart: always
    networks:
      - movies-network

  filebeat:
    image: elastic/filebeat:8.15.2
    container_name: movies-notifications-filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./log:/var/log
    restart: always
    networks:
      - movies-network
    healthcheck:
      test: ["CMD", "pidof", "filebeat"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  movies-network:
    name: movies-network
    external: true