"""update

Revision ID: b507872084f3
Revises: 98a506ad4299
Create Date: 2024-12-06 18:26:40.079910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b507872084f3'
down_revision: Union[str, None] = '98a506ad4299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genrefilmwork', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('personfilmwork', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personfilmwork', 'updated_at')
    op.drop_column('genrefilmwork', 'updated_at')
    # ### end Alembic commands ###
