"""Update User tabke.

Revision ID: 66a2aea65ba7
Revises: 1de719570c73
Create Date: 2024-12-06 16:28:44.822147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66a2aea65ba7'
down_revision: Union[str, None] = '1de719570c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('user', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('surname', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'surname')
    op.drop_column('user', 'name')
    op.create_table('session_202706',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['refresh_token_id'], ['refreshtoken.id'], name='session_refresh_token_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='session_user_id_fkey'),
    sa.PrimaryKeyConstraint('created_at', 'id', name='session_202706_pkey')
    )
    op.create_table('session_202811',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['refresh_token_id'], ['refreshtoken.id'], name='session_refresh_token_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='session_user_id_fkey'),
    sa.PrimaryKeyConstraint('created_at', 'id', name='session_202811_pkey')
    )
    op.create_table('session_202905',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['refresh_token_id'], ['refreshtoken.id'], name='session_refresh_token_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='session_user_id_fkey'),
    sa.PrimaryKeyConstraint('created_at', 'id', name='session_202905_pkey')
    )
    op.create_table('session_202612',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['refresh_token_id'], ['refreshtoken.id'], name='session_refresh_token_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='session_user_id_fkey'),
    sa.PrimaryKeyConstraint('created_at', 'id', name='session_202612_pkey')
    )
    op.create_table('session_202606',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['refresh_token_id'], ['refreshtoken.id'], name='session_refresh_token_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='session_user_id_fkey'),
    sa.PrimaryKeyConstraint('created_at', 'id', name='session_202606_pkey')
    )
    op.create_table('session_202512',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['refresh_token_id'], ['refreshtoken.id'], name='session_refresh_token_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='session_user_id_fkey'),
    sa.PrimaryKeyConstraint('created_at', 'id', name='session_202512_pkey')
    )
    op.create_table('session_202412',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['refresh_token_id'], ['refreshtoken.id'], name='session_refresh_token_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='session_user_id_fkey'),
    sa.PrimaryKeyConstraint('created_at', 'id', name='session_202412_pkey')
    )
    op.create_table('session_202806',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['refresh_token_id'], ['refreshtoken.id'], name='session_refresh_token_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='session_user_id_fkey'),
    sa.PrimaryKeyConstraint('created_at', 'id', name='session_202806_pkey')
    )
    op.create_table('session_202506',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['refresh_token_id'], ['refreshtoken.id'], name='session_refresh_token_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='session_user_id_fkey'),
    sa.PrimaryKeyConstraint('created_at', 'id', name='session_202506_pkey')
    )
    op.create_table('session_202712',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['refresh_token_id'], ['refreshtoken.id'], name='session_refresh_token_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='session_user_id_fkey'),
    sa.PrimaryKeyConstraint('created_at', 'id', name='session_202712_pkey')
    )
    # ### end Alembic commands ###
