CREATE DATABASE auth;
GRANT ALL PRIVILEGES ON DATABASE auth TO postgres;
CREATE DATABASE billing;
GRANT ALL PRIVILEGES ON DATABASE billing TO postgres;
CREATE DATABASE content;
GRANT ALL PRIVILEGES ON DATABASE content TO postgres;