services:
  postgres:
    image: postgres:16
    container_name: movies-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/initdb:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks: 
      - movies-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: movies-pgadmin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
    env_file:
      - .env
    networks:
      -  movies-network
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 10s
      start_period: 160s
      retries: 3

  redis:
    image: redis:7.4.0
    container_name: movies-redis
    ports:
        - "6379:6379"
    volumes:
        - ./redis/data:/data/
    command: redis-server --databases 2
    networks:
      -  movies-network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:latest
    container_name: movies-kafka
    ports:
      - "9094:9094"
    volumes:
      - ./kafka/data:/bitnami/kafka/data
    env_file:
      - .env
    networks:
      - movies-network
    restart: always
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9094", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  movies-network:
    name: movies-network


